/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PembeliController;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author aim
 */
public class FormPembeli extends javax.swing.JInternalFrame {
    
    


    /**
     * Creates new form FormPembeli
     */
    public FormPembeli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        noPembelianTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();
        alamatTextField = new javax.swing.JTextField();
        teleponTextField = new javax.swing.JTextField();
        simpanToggleButton = new javax.swing.JToggleButton();
        hapusToggleButton = new javax.swing.JToggleButton();
        tutupToggleButton = new javax.swing.JToggleButton();
        daftarToggleButton = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Master Data Pembeli");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("No. Pembelian");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Telepon");

        noPembelianTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noPembelianTextFieldKeyPressed(evt);
            }
        });

        simpanToggleButton.setText("Simpan");
        simpanToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanToggleButtonActionPerformed(evt);
            }
        });

        hapusToggleButton.setText("Hapus");
        hapusToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusToggleButtonActionPerformed(evt);
            }
        });

        tutupToggleButton.setText("Tutup");
        tutupToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupToggleButtonActionPerformed(evt);
            }
        });

        daftarToggleButton.setText("Daftar");
        daftarToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaTextField)
                            .addComponent(alamatTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noPembelianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(daftarToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(teleponTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpanToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(hapusToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(tutupToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(noPembelianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daftarToggleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanToggleButton)
                    .addComponent(hapusToggleButton)
                    .addComponent(tutupToggleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setNoPembelian(String noPembelian) {
        noPembelianTextField.setText(noPembelian);
    }
    
    public void setNama(String nama){
        namaTextField.setText(nama);
    }
    
    public void setAlamat(String alamat){
        alamatTextField.setText(alamat);
    }
    
    public void setTelepon(String telepon){
        teleponTextField.setText(telepon);
    }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void noPembelianTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noPembelianTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            new PembeliController().cari(noPembelianTextField);
        }

    }//GEN-LAST:event_noPembelianTextFieldKeyPressed

    private void daftarToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarToggleButtonActionPerformed
        // TODO add your handling code here:
        new PembeliController().tampilkanDaftar();
    }//GEN-LAST:event_daftarToggleButtonActionPerformed

    private void simpanToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanToggleButtonActionPerformed
        // TODO add your handling code here:
        new PembeliController().simpan(noPembelianTextField, namaTextField, alamatTextField, teleponTextField);
    }//GEN-LAST:event_simpanToggleButtonActionPerformed

    private void hapusToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusToggleButtonActionPerformed
        // TODO add your handling code here:
        new PembeliController().hapus(noPembelianTextField);
    }//GEN-LAST:event_hapusToggleButtonActionPerformed

    private void tutupToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupToggleButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tutupToggleButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTextField;
    private javax.swing.JToggleButton daftarToggleButton;
    private javax.swing.JToggleButton hapusToggleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField noPembelianTextField;
    private javax.swing.JToggleButton simpanToggleButton;
    private javax.swing.JTextField teleponTextField;
    private javax.swing.JToggleButton tutupToggleButton;
    // End of variables declaration//GEN-END:variables
}
