/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KwitansiController;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aim
 */
public class FormKwitansi extends javax.swing.JInternalFrame {
    private DefaultTableModel kwitansiDefaultTableModel;
    


    /**
     * Creates new form FormKwitansi
     */
    public FormKwitansi() {
        initComponents();
        
        kwitansiDefaultTableModel = (DefaultTableModel) kwitansiTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpanButton = new javax.swing.JButton();
        alamatTextField = new javax.swing.JTextField();
        teleponTextField = new javax.swing.JTextField();
        kwitansiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kwitansiTable = new javax.swing.JTable();
        tutupButton = new javax.swing.JButton();
        namaTextField = new javax.swing.JTextField();
        daftarButton = new javax.swing.JButton();
        kelasLabel = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        noPembeliLabel = new javax.swing.JLabel();
        noBeliTextField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Kwitansi");

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        alamatTextField.setEditable(false);

        teleponTextField.setEditable(false);

        kwitansiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Kwitansi"));

        kwitansiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "No. Pembeli", "Judul Buku", "Jumlah", "Harga"
            }
        ));
        kwitansiTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kwitansiTablePropertyChange(evt);
            }
        });
        kwitansiTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kwitansiTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(kwitansiTable);
        kwitansiTable.getColumnModel().getColumn(0).setMinWidth(100);
        kwitansiTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        kwitansiTable.getColumnModel().getColumn(0).setMaxWidth(100);

        javax.swing.GroupLayout kwitansiPanelLayout = new javax.swing.GroupLayout(kwitansiPanel);
        kwitansiPanel.setLayout(kwitansiPanelLayout);
        kwitansiPanelLayout.setHorizontalGroup(
            kwitansiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kwitansiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        kwitansiPanelLayout.setVerticalGroup(
            kwitansiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kwitansiPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        tutupButton.setText("Tutup");
        tutupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupButtonActionPerformed(evt);
            }
        });

        namaTextField.setEditable(false);

        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        kelasLabel.setText("Telepon");

        semesterLabel.setText("Alamat");

        noPembeliLabel.setText("No. Pembeli");

        noBeliTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                noBeliTextFieldKeyPressed(evt);
            }
        });

        namaLabel.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kwitansiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLabel)
                            .addComponent(noPembeliLabel)
                            .addComponent(semesterLabel)
                            .addComponent(kelasLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noBeliTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(daftarButton))
                            .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tutupButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(simpanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noPembeliLabel)
                    .addComponent(noBeliTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daftarButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(tutupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(semesterLabel)
                            .addComponent(alamatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelasLabel)
                            .addComponent(teleponTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(kwitansiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setNoPembeli(String no_beli){
        noBeliTextField.setText(no_beli);
    }
    
    public void setNama(String nama){
        namaTextField.setText(nama);
    }
    
    public void setAlamat(String alamat){
	 alamatTextField.setText(alamat);
    }
    
    public void setTelepon(String telepon){
	teleponTextField.setText(telepon);
    }
    
    public void setJudulBuku(String judul){
	kwitansiTable.setValueAt(judul, kwitansiTable.getSelectedRow(), 1);
    }
    
    public void setTambahKwitansi(Object[] kwitansiBuku){
        kwitansiDefaultTableModel.insertRow( kwitansiDefaultTableModel.getRowCount(), kwitansiBuku);                    
    }
    
    public void clearKwitansiTable(){
        kwitansiDefaultTableModel.setRowCount(0);
    }
    
    
    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        new KwitansiController().simpan(noBeliTextField, kwitansiTable);
        
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void kwitansiTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kwitansiTablePropertyChange
        // TODO add your handling code here:
        if (kwitansiTable.getSelectedRowCount()>0){
            if (kwitansiTable.getSelectedColumn()==0){
                String kode_buku = "";
                try{
                    kode_buku = kwitansiTable.getValueAt(kwitansiTable.getSelectedRow(), 0).toString();
                }catch (Exception ex){}
                if (!kode_buku.equals("")){
                    new KwitansiController().cariBuku(kode_buku);
                }
            }
        }

        
    }//GEN-LAST:event_kwitansiTablePropertyChange

    private void kwitansiTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kwitansiTableKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            if (kwitansiTable.getSelectedRow() == (kwitansiTable.getRowCount()-1)){
                if (kwitansiTable.getSelectedColumn()==0){
                    kwitansiDefaultTableModel.insertRow(kwitansiDefaultTableModel.getRowCount(), new Object[]{});
                }
            }
        }

        
    }//GEN-LAST:event_kwitansiTableKeyPressed

    private void tutupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_tutupButtonActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // TODO add your handling code here:
        new KwitansiController().tampilkanDaftarPembeli();
       
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void noBeliTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noBeliTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            new KwitansiController().cariPembeli(noBeliTextField);
        }

        
    }//GEN-LAST:event_noBeliTextFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatTextField;
    private javax.swing.JButton daftarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JPanel kwitansiPanel;
    private javax.swing.JTable kwitansiTable;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JTextField noBeliTextField;
    private javax.swing.JLabel noPembeliLabel;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JButton simpanButton;
    private javax.swing.JTextField teleponTextField;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
}
