/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Dimension;
import java.awt.Toolkit;


/**
 *
 * @author aim
 */
public class FormUtama extends javax.swing.JFrame {
    public static FormPembeli formPembeli = new FormPembeli();
    public static FormBuku formBuku = new FormBuku();
    public static FormKwitansi formKwitansi = new FormKwitansi();
    public static FormLaporanKwitansi formLaporanKwitansi = new FormLaporanKwitansi();

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        aturFrame(0.9,true);
    }
    
    private void aturFrame(double skala, boolean tengah){
        Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)(skala*dimensi.getWidth()),
                (int)(skala*dimensi.getHeight()));
        if (tengah){
            setLocation((int)((dimensi.getWidth()-getWidth())/2),
                    (int)((dimensi.getHeight()-getHeight())/2));
        }
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplikasiMenu = new javax.swing.JMenu();
        keluarMenuItem = new javax.swing.JMenuItem();
        masterDataMenu = new javax.swing.JMenu();
        pembeliMenuItem = new javax.swing.JMenuItem();
        bukuMenuItem = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        kwitansiMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        laporanKwitansiMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pembelian Buku");

        aplikasiMenu.setText("Aplikasi");

        keluarMenuItem.setText("Keluar");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        aplikasiMenu.add(keluarMenuItem);

        jMenuBar1.add(aplikasiMenu);

        masterDataMenu.setText("Master Data");

        pembeliMenuItem.setText("Pembeli");
        pembeliMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembeliMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(pembeliMenuItem);

        bukuMenuItem.setText("Buku");
        bukuMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(bukuMenuItem);

        jMenuBar1.add(masterDataMenu);

        transaksiMenu.setText("Transaksi");

        kwitansiMenuItem.setText("Kwitansi");
        kwitansiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kwitansiMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(kwitansiMenuItem);

        jMenuBar1.add(transaksiMenu);

        laporanMenu.setText("Laporan");

        laporanKwitansiMenuItem.setText("Laporan Kwitansi");
        laporanKwitansiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanKwitansiMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(laporanKwitansiMenuItem);

        jMenuBar1.add(laporanMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void pembeliMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembeliMenuItemActionPerformed
        // TODO add your handling code here:
        if(formPembeli.isVisible()){
            try {
                formPembeli.setSelected(true);
            } catch (Exception ex) {}
        } else {
            formPembeli = new FormPembeli();
            mdiDesktopPane.add(formPembeli);
            formPembeli.setVisible(true);
        }
    }//GEN-LAST:event_pembeliMenuItemActionPerformed

    private void bukuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuMenuItemActionPerformed
        // TODO add your handling code here:
         if(formBuku.isVisible()){
            try {
                formBuku.setSelected(true);
            } catch (Exception ex) {}
        } else {
            formBuku = new FormBuku();
            mdiDesktopPane.add(formBuku);
            formBuku.setVisible(true);
        }
    }//GEN-LAST:event_bukuMenuItemActionPerformed

    private void kwitansiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kwitansiMenuItemActionPerformed
        // TODO add your handling code here:
        if(formKwitansi.isVisible()){
            try {
                formKwitansi.setSelected(true);
            } catch (Exception ex) {}
        } else {
            formKwitansi = new FormKwitansi();
            mdiDesktopPane.add(formKwitansi);
            formKwitansi.setVisible(true);
        }
    }//GEN-LAST:event_kwitansiMenuItemActionPerformed

    private void laporanKwitansiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanKwitansiMenuItemActionPerformed
        // TODO add your handling code here:
        if (formLaporanKwitansi.isVisible()) {
            try {
                formLaporanKwitansi.setSelected(true);
            } catch (Exception ex) {}
        } else {
            formLaporanKwitansi = new FormLaporanKwitansi();
            mdiDesktopPane.add(formLaporanKwitansi);
            formLaporanKwitansi.setVisible(true);
        }

    }//GEN-LAST:event_laporanKwitansiMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aplikasiMenu;
    private javax.swing.JMenuItem bukuMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem keluarMenuItem;
    private javax.swing.JMenuItem kwitansiMenuItem;
    private javax.swing.JMenuItem laporanKwitansiMenuItem;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenu masterDataMenu;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenuItem pembeliMenuItem;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
